Arch: win64
CompatData: ''
Creation_Date: '2025-06-16 21:32:58.108993'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.6.2
Environment: Custom
Environment_Variables: {}
External_Programs:
    137af832-e55a-437d-b139-ee0452f68b95:
        arguments: null
        dxvk: null
        dxvk_nvapi: null
        executable: speed.exe
        folder: ~/Games/Speed
        fsr: null
        gamescope: null
        icon: com.usebottles.bottles-program
        id: 137af832-e55a-437d-b139-ee0452f68b95
        name: Bottle init success!
        path: ~/Games/Speed/speed.exe
        post_script: null
        pre_script: null
        pulseaudio_latency: null
        removed: null
        virtual_desktop: null
        vkd3d: null
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- gecko
- andale32
- arialb32
- comic32
- georgi32
- impact32
- tahoma32
- trebuc32
- verdan32
- webdin32
- allfonts
- d3dx11
- d3dcompiler_42
- d3dcompiler_46
- consolas
- dotnet40
- dotnet452
- dotnetcoredesktop9
- dx8vb
- physx
- vcredist2022
- vcredist6sp6
- vcredist2013
- webview2
- riched20
- vcredist2015
- msxml6
- xinput
- xna40
- xact_x64
- xact
- vcredist2008
- vcredist2010
- vcredist2012
- dotnetcoredesktop3
- dotnetcoredesktop6
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.9.0
Name: Moon
Parameters:
    custom_dpi: 141
    decorated: true
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: true
    fsr_quality_mode: performance
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: true
    gamescope: false
    gamescope_borderless: true
    gamescope_fps: 60.0
    gamescope_fps_no_focus: 0.0
    gamescope_fullscreen: false
    gamescope_game_height: 900.0
    gamescope_game_width: 1600.0
    gamescope_scaling: false
    gamescope_window_height: 900.0
    gamescope_window_width: 1600.0
    latencyflex: true
    mangohud: false
    mangohud_display_on_game_start: true
    mouse_warp: false
    obsvkc: false
    pulseaudio_latency: false
    renderer: vulkan
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1920x1080
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: Pluto
Runner: kron4ek-wine-10.10-staging-tkg-ntsync-amd64-wow64
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2025-06-21 22:39:48.512183'
VKD3D: vkd3d-proton-2.14.1
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
